/* ============================================================================
   CARBambase — species_info.js
   Researched trait notes for the Species tab, keyed by scientific name (matching
   bamboolist.csv / OCC_SPECIES). Fields: habit (type/growth habit), height (culm
   height), diameter (culm diameter), uses (primary uses), description.
   Compiled from public botanical sources (Kew POWO, PROSEA, published floras,
   horticultural databases). "" = could not be verified; "(genus-level)" marks a
   value taken from the genus where species-level data was unavailable.
   Records-in-database and recorded municipalities are computed in data.js.
   ========================================================================== */
window.SPECIES_INFO = {
  /* ---- species with occurrence records ---- */
  "Bambusa vulgaris": {
    habit: "Open-clumping (sympodial), erect to arching",
    height: "10–20 m",
    diameter: "4–10 cm",
    uses: "Light construction, fencing, scaffolding, furniture, musical instruments, handicrafts, paper pulp; shoots occasionally eaten",
    description: "One of the most widely planted and easily grown bamboos in the world, forming moderately loose, thornless clumps of glossy green culms that are straight below and arch or droop at the tips.",
  },
  "Bambusa spinosa": {
    habit: "Dense clumping (sympodial), thorny/spiny",
    height: "15–25 m",
    diameter: "up to 15 cm (walls 2–3 cm, sometimes solid)",
    uses: "Edible shoots, living fences and windbreaks, riverbank erosion control, scaffolding, basketry, furniture, chopsticks, utensils, paper pulp",
    description: "The common spiny 'kawayan-tinik' of the Philippines — a densely clumping bamboo whose lower branches are armed with curved thorns. Its thick-walled culms and shoot-producing clumps make it a mainstay for erosion control, fencing and heavy handicraft.",
  },
  "Dendrocalamus asper": {
    habit: "Clumping (sympodial), erect",
    height: "20–30 m",
    diameter: "15–25 cm",
    uses: "Heavy construction (poles, scaffolding, bridges), furniture, handicrafts, edible sweet shoots, paper pulp",
    description: "One of the largest cultivated bamboos, forming dense clumps of robust, thick-walled, straight culms; lower nodes of young culms bear distinctive golden-brown hairs. Widely grown across Southeast Asia for durable timber-grade poles and prized edible shoots.",
  },
  "Dendrocalamus merrillianus": {
    habit: "Clumping (sympodial), culms drooping",
    height: "~15 m (to 20 m)",
    diameter: "~8 cm (walls ~1/3 of diameter; dense)",
    uses: "Edible shoots, furniture, structural construction (dense culms with small hollow)",
    description: "A Philippine-endemic clumping bamboo ('bayog') with drooping culms and aerial roots on the lower nodes; culms are notably dense with a small central hollow, favouring structural use. Often found near water and tolerant of salinity; valued for shoots and furniture.",
  },
  "Schizostachyum lumampao": {
    habit: "Densely tufted clumping (sympodial), erect",
    height: "10–15 m",
    diameter: "4–8 cm (walls ~4–5 mm, thin)",
    uses: "Sawali (woven matting), fencing, baskets, poles, spears, fish pens, flutes, ply-bamboo panels, paper pulp",
    description: "A slender, thin-walled Philippine endemic ('buho') forming dense clumps with long internodes and many branches near the top. Its easily split culms are the classic material for sawali matting and light woven handicraft.",
  },
  "Phyllostachys aurea": {
    habit: "Running (monopodial), spreads by rhizomes",
    height: "6–10 m (often 3–6 m in gardens)",
    diameter: "2.5–5 cm",
    uses: "Ornamental screens and hedges, walking sticks, umbrella handles, craftwork; edible shoots",
    description: "A vigorous running temperate bamboo whose erect green culms turn golden-yellow in sun, with distinctive compressed, swollen lower internodes ('fishpole/tortoise-shell'). Popular as an ornamental screen; being a runner, it spreads and needs containment.",
  },
  "Bambusa oldhamii": {
    habit: "Clumping (sympodial), erect",
    height: "up to 20 m",
    diameter: "up to 10 cm",
    uses: "Ornamental screens, timber (furniture, scaffolding, construction, crafts), edible sweet shoots",
    description: "A large 'giant timber' clumping bamboo with straight, thick-walled olive-green culms and a tidy upright habit; one of the most widely cultivated clumpers worldwide, valued as a screen and for its crisp, sweet shoots.",
  },
  "Gigantochloa levis": {
    habit: "Clumping (sympodial), erect",
    height: "15–20 m (to 30 m)",
    diameter: "6–13 cm (walls 1–3 cm)",
    uses: "Good edible shoots, house construction and framework, plaited walls, furniture, rafts, fish traps, outriggers, fish pens",
    description: "A tall clump-forming bamboo ('bolo') with erect, fairly thin-walled culms; in the Philippines it is prized for quality edible shoots and for versatile culms used in construction, furniture and fishing gear. Cultivated and locally naturalized.",
  },
  "Bambusa vulgaris var. striata": {
    habit: "Open-clumping (sympodial), erect to arching",
    height: "10–15 m",
    diameter: "5–8 cm",
    uses: "Ornamental (hedges, slope/riverbank erosion control), light-construction poles, furniture, baskets",
    description: "The showy yellow-culmed form of common bamboo, its glossy golden culms randomly striped with green. One of the most widely planted ornamental bamboos in the tropics, also used for light poles, furniture and stabilizing banks.",
  },
  "Fimbribambusa horsfieldii": {
    habit: "Clumping (sympodial), erect and straggling; spineless, no nodal roots",
    height: "up to 18 m",
    diameter: "~0.8–1 cm (slender, thin-walled)",
    uses: "",
    description: "A little-known clumping bamboo ('anes') of East Java and the Philippines, with slender, leaning, thin-walled culms and swollen nodes. Recorded as native in Benguet and Mountain Province; documented uses were not found.",
  },
  "Dinochloa acutiflora": {
    habit: "Climbing/scrambling (zigzag culms), needs support",
    height: "9–20 m (climbing length)",
    diameter: "2–4 cm",
    uses: "Weaving and basketry, rattan substitute, steam-bent articles, bent furniture parts, bag handles",
    description: "A native climbing bamboo ('bikal') with slender, flexuose, zigzag culms that scramble over vegetation or slopes rather than standing erect; the pliable culm strips serve as a rattan substitute for weaving and bentwork. DAO-listed as threatened.",
  },
  "Dendrocalamus latiflorus": {
    habit: "Densely tufted clumping (sympodial), erect with pendulous tip",
    height: "14–25 m",
    diameter: "8–20 cm (walls 5–30 mm)",
    uses: "Prized sweet edible shoots, construction, water pipes, rafts, baskets, paper pulp",
    description: "A large clumping 'sweet bamboo' (machiku) from southern China and Taiwan, densely tufted with tall, thick-walled culms; famous for exceptionally sweet, tender shoots and also used for construction, rafts and pulp.",
  },
  "Sphaerobambos philippinensis": {
    habit: "Clumping (sympodial), erect",
    height: "4–6 m (reported to ~9 m)",
    diameter: "~5 cm (thin-walled, long internodes)",
    uses: "Propping banana bunches, riverbank stabilization / erosion control, edible shoots",
    description: "A Philippine-endemic clumping bamboo ('laak') with erect, thin-walled culms and long internodes; historically valued in Davao for propping heavy Cavendish banana bunches and for bank stabilization, and a source of edible shoots.",
  },
  "Bambusa multiplex": {
    habit: "Clumping (sympodial), erect and dense",
    height: "3–5 m (to ~7 m)",
    diameter: "1–3 cm",
    uses: "Ornamental hedges, borders and screens; containers and bonsai",
    description: "A small, dense clumping bamboo with slender green culms and fine, fern-like foliage that responds well to trimming — one of the most popular ornamental hedge and screen bamboos, with cultivars such as 'Fernleaf' and 'Golden Goddess'.",
  },
  "Bambusa ventricosa": {
    habit: "Clumping (sympodial), erect to arching",
    height: "3–16 m (dwarfed when stressed)",
    diameter: "~4–7 cm",
    uses: "Ornamental — screens, hedges, potted specimens and bonsai",
    description: "An ornamental clumping bamboo famous for the swollen, belly-like internodes that form when it is grown pot-bound or water-stressed; grown well and unstressed it becomes tall with normal culms. Native to southern China.",
  },
  "Guadua angustifolia": {
    habit: "Open-clumping (sympodial), erect, thorny",
    height: "15–25 m",
    diameter: "10–22 cm at base",
    uses: "Heavy structural construction, engineered building elements, furniture, handicrafts",
    description: "A giant neotropical 'iron bamboo' from South America and one of the strongest bamboos, with tall, straight, thick-walled dark-green culms; a premier structural building material. Grown in the Cordillera as an exotic.",
  },
  "Schizostachyum lima": {
    habit: "Clumping (sympodial), erect with drooping tip; thin-walled, spineless",
    height: "7–10(–13) m",
    diameter: "2–4 cm (walls ~2 mm)",
    uses: "Sawali, fishing rods, flutes and musical instruments; long internodes carved as containers (molasses, tobacco)",
    description: "A Philippine-endemic erect, thin-walled bamboo ('anos') distinguished by unusually long internodes (up to about 1 m); the internodes are prized for sawali, fishing rods, flutes and decoratively low-relief carved containers.",
  },
  "Cyrtochloa toppingii": {
    habit: "Climbing/scandent (scrambling, zigzag culms)",
    height: "several m (climbing; genus-level)",
    diameter: "~2.5–3 cm (genus-level)",
    uses: "Weaving and basketry (genus-level)",
    description: "A Philippine-endemic climbing ('scandent') bamboo of the genus Cyrtochloa, which is restricted to the Philippines; its slender zigzag culms scramble over vegetation rather than standing erect. Local names include banos/bukawe. Species-level dimensions are poorly documented.",
  },
  "Cyrtochloa puser": {
    habit: "Climbing/scandent, zigzag, drooping at tip",
    height: "7–10 m",
    diameter: "2.5–3 cm",
    uses: "Basket weaving and related crafts",
    description: "A Philippine-endemic climbing bamboo of Luzon ('puser') with woody, zigzag, scrambling culms 7–10 m long and about 2.5–3 cm across; used for basket-weaving and crafts. DAO-listed as Vulnerable.",
  },
  "Cyrtochloa major": {
    habit: "Climbing/scandent (scrambling, zigzag culms)",
    height: "several m (climbing; genus-level)",
    diameter: "(genus-level; not well documented)",
    uses: "Weaving and basketry (genus-level)",
    description: "A Philippine-endemic climbing bamboo ('bikal-baboy', formerly Dinochloa major); like other Cyrtochloa it scrambles over vegetation with slender zigzag culms rather than standing erect. Species-specific dimensions are poorly documented.",
  },
  "Phyllostachys nigra": {
    habit: "Running (monopodial), erect",
    height: "6–11 m",
    diameter: "2–5 cm",
    uses: "Ornamental specimen and screens, containers; furniture, musical instruments, decorative panels and inlays",
    description: "A striking running temperate bamboo whose slender green culms mature to a polished ebony-black over 2–3 years, contrasting with fine green foliage; one of the most ornamental bamboos, also used for furniture, instruments and inlays. A runner that needs containment.",
  },
  "Gigantochloa atroviolacea": {
    habit: "Clumping (sympodial), tufted, erect",
    height: "8–12 m",
    diameter: "6–8 cm (walls 5–8 mm)",
    uses: "Traditional musical instruments (angklung, calung), construction, furniture, decorative panels, fencing; edible shoots",
    description: "A medium, dense clumping tropical bamboo from Java whose culms mature from dark green to purplish-black with whitish nodes; famed for Sundanese musical instruments and also used for construction, furniture and handicraft. Grown here as an exotic.",
  },
  "Bambusa tuldoides": {
    habit: "Clumping (sympodial), erect with nodding tip; tightly clumped, non-invasive",
    height: "6–15 m",
    diameter: "3–5 cm",
    uses: "Punting/fishing poles, strong timber, hedges and windbreaks, screening, construction, furniture, crafts",
    description: "A tightly clumping 'punting-pole' bamboo with erect, thick-walled straight green culms that nod at the tip; hardy and non-invasive, valued for poles, strong small timber, hedges and crafts, and as a screening ornamental.",
  },
  "Sasaella masamuneana cv. 'Albostriata'": {
    habit: "Running (monopodial), dwarf groundcover",
    height: "0.6–1.8 m",
    diameter: "under 1 cm (slender)",
    uses: "Ornamental groundcover, lawn substitute, containers, houseplant",
    description: "A dwarf running bamboo grown as an ornamental groundcover, its thick dark-green leaves boldly striped white/cream; tolerates mowing (which refreshes the variegation) and suits containers. The 'Albostriata' cultivar of Sasaella masamuneana.",
  },
  "Rhipidocladum sp.": {
    habit: "Woody bamboo with fan-like branch clusters (genus-level)",
    height: "~9–15 m (genus-level)",
    diameter: "slender, under ~2.5 cm (genus-level)",
    uses: "(undetermined; identified to genus only)",
    description: "Identified only to genus. Rhipidocladum is a group of New World (Latin American) woody bamboos with slender culms and characteristic fan-like ('rhipido-') branch clusters, often looking palm-like. The specific species in the collection is undetermined, so species-level traits cannot be given.",
  },

  /* ---- species not in the occurrence database (BSU Forestry Nursery) ---- */
  "Schizostachyum brachycladum": {
    habit: "Clumping (sympodial), erect and straight",
    height: "7–15 m",
    diameter: "6–10 cm (walls 3–5 mm)",
    uses: "Construction, crafts, carved containers, water pipes, roofing, banana props, cooking glutinous rice (lemang); ceremonial use; ornamental",
    description: "An erect clumping bamboo with striking bright-yellow, green-striped culms ('buhong dilau'); widely grown in Southeast Asia for construction, crafts and carved containers and used ceremonially in parts of Indonesia. Naturalized in the region.",
  },
  "Phyllostachys edulis": {
    habit: "Running (monopodial), erect; vigorous spreader",
    height: "18–23 m (to 28 m)",
    diameter: "11–18 cm",
    uses: "Premier construction timber (flooring, furniture, laminated board, scaffolding, charcoal), edible spring shoots (major crop), bamboo textile/rayon",
    description: "The famous 'moso', the giant temperate running bamboo of East Asia and the backbone of the bamboo timber and shoot industries; velvety grey-green new culms mature deep green. Extremely fast-growing but strongly running and potentially invasive.",
  },
  "Phyllostachys aureosulcata": {
    habit: "Running (monopodial), erect; aggressive spreader",
    height: "9–14 m",
    diameter: "4–6.5 cm",
    uses: "Ornamental (hedge, screen, windbreak, grove, erosion control), edible shoots",
    description: "A cold-hardy running bamboo ('yellow-groove') with green culms marked by a yellow groove (sulcus), the lower culms often bending in a zigzag; grown ornamentally as a screen or hedge and for good-quality edible shoots. Spreads aggressively.",
  },
  "Phyllostachys dulcis": {
    habit: "Running (monopodial), erect and arching; vigorous spreader",
    height: "to ~12 m",
    diameter: "5–7.5 cm",
    uses: "Prized edible shoots (among the finest), hedge/screen, landscaping, construction, paper and textile raw material",
    description: "A running temperate bamboo ('sweetshoot') with soft green, relatively thick culms bearing a white ring at the nodes; most esteemed for its excellent, sweet edible shoots — one of the finest culinary bamboos in China. A vigorous runner.",
  },
  "Dendrocalamus strictus": {
    habit: "Clumping (sympodial), dense; culms often nearly solid",
    height: "8–20 m",
    diameter: "2.5–8 cm (thick-walled; solid in dry sites)",
    uses: "Paper-mill pulpwood, edible shoots, light construction, furniture, musical instruments, mats, tool handles, agricultural implements",
    description: "A medium clumping bamboo ('male/solid/Calcutta bamboo') whose thick-walled culms are nearly solid in drier sites; a major pulpwood in India and used for construction, furniture, tool handles and crafts. Very drought- and temperature-tolerant.",
  },
  "Chimonobambusa quadrangularis": {
    habit: "Running (monopodial), erect; spreads by rhizomes",
    height: "5–7.6 m",
    diameter: "2–3.8 cm",
    uses: "Novelty walking sticks (square culms), craftwork, edible shoots",
    description: "A running temperate bamboo whose thick-walled culms are distinctively squarish in cross-section; grown ornamentally and used for novelty walking sticks and crafts, with edible young shoots. Spreads by rhizomes.",
  },
  "Chimonobambusa marmorea": {
    habit: "Running (monopodial), erect; active spreader",
    height: "1.2–3 m",
    diameter: "~1.3 cm",
    uses: "Ornamental hedge, containers/indoor plant, erosion control",
    description: "A small running bamboo ('marbled bamboo') whose new shoots are mottled creamy-white and purple; grown as an ornamental hedge, container or indoor plant and for erosion control. Spreads vigorously by rhizomes.",
  },
  "Chimonobambusa neopurpurea": {
    habit: "Running (monopodial) (genus-level)",
    height: "several m (genus-level)",
    diameter: "1–4 cm (genus-level)",
    uses: "Ornamental; edible winter shoots (genus-level)",
    description: "A running temperate bamboo of the genus Chimonobambusa, grown for ornamental (often purple-tinged) culms and edible winter shoots. Species-specific dimensions were not well documented, so genus-level traits are given.",
  },
  "Pseudosasa amabilis": {
    habit: "Running (monopodial), erect and woody",
    height: "6–13 m",
    diameter: "2–6 cm",
    uses: "Premier split-cane fishing rods (Tonkin cane), furniture, flooring, handicrafts",
    description: "The famous 'Tonkin cane' — an East Asian running bamboo with straight, strong, thin-walled culms that are the classic material for split-cane fly-fishing rods, and also used for furniture, flooring and crafts. Bare in the lower half, leafy above.",
  },
  "Shibataea kumasaca": {
    habit: "Dwarf running (leptomorph) but slow and clump-like; compact",
    height: "~1.5 m",
    diameter: "~0.6 cm (slender)",
    uses: "Ornamental — edging, groundcover, low hedge, containers",
    description: "A dwarf, compact bamboo ('ruscus bamboo') with short, broad ruscus-like leaves and slender upright canes; it spreads slowly and is easily controlled, making it ideal for low hedges, edging, groundcover and containers. Prefers shade.",
  },
  "Bambusa textilis": {
    habit: "Clumping (sympodial), tight and erect; non-invasive",
    height: "6–12 m",
    diameter: "~3–5 cm",
    uses: "Weaving and basketry (a choice weaving bamboo), light construction, ornamental screen",
    description: "The 'weaver's bamboo' — a tightly clumping, non-invasive bamboo with very straight, upright culms, smooth nodes and delicate cascading foliage; its strong, pliable, node-free fibres make it a top choice for weaving and basketry, and it is popular as an elegant screen.",
  },
  "Bambusa heterostachya": {
    habit: "Clumping (sympodial), erect with weeping tops",
    height: "6–15 m (dwarf/variegated forms 3–4 m)",
    diameter: "3–5 cm (walls 0.8–1 cm)",
    uses: "Ornamental hedge and screen, borders, windbreaks",
    description: "An evergreen clumping bamboo ('Malay dwarf') with erect green culms that weep at the tips and can be shaped by pruning into dense tufts; grown mainly as a bushy ornamental hedge, border or windbreak, with variegated and dwarf forms in cultivation.",
  },
  "Nastus elatus": {
    habit: "Clumping (sympodial), erect with weeping tops (sometimes scrambling)",
    height: "15–20 m",
    diameter: "5–8 cm",
    uses: "Prized edible shoots (eaten raw), musical instruments, containers, construction, woven walls/floors, utensils",
    description: "A tall clumping bamboo from New Guinea ('New Guinea sweet shoot') with light-green culms and soft, fine foliage; renowned for exceptionally sweet shoots that can be eaten raw, and also used for construction, woven walling and utensils.",
  },
  "Neololeba atra": {
    habit: "Clumping but scandent/scrambling; forms dense thickets",
    height: "5–8 m",
    diameter: "2–4 cm (thin-walled)",
    uses: "Basketry and handicrafts (skin used), building material, thatching/binding, fish traps, screens",
    description: "A tropical thin-walled bamboo ('long pipe') from New Guinea and Indonesia that scrambles into dense clumps; its thin culms are used skin-only for quality basketry and handicraft, plus building, thatching binders, fish traps and screens.",
  },
  "Dinochloa scandens": {
    habit: "Climbing/scrambling (zigzag, climbs by looping), freely branching",
    height: "up to 30 m (climbing length)",
    diameter: "1.5–3 cm",
    uses: "Rough carrying baskets (resilient zigzag culms), weaving",
    description: "A vigorous native climbing bamboo ('usiu' / zigzag bamboo) with smooth green, zig-zagging culms up to ~30 m that loop and scramble over forest vegetation into tangled masses; the resilient culms are woven into rough carrying baskets. Widely distributed in the central and southern Philippines.",
  },
  "Dinochloa luconiae": {
    habit: "Climbing/scrambling (zigzag culms), needs support",
    height: "to ~25 m (climbing length)",
    diameter: "1–2 cm (slender)",
    uses: "Weaving and basketry (rattan-like; genus-level)",
    description: "A native climbing bamboo ('bikal') ranging from Borneo to Luzon; very similar to zigzag bamboo (Dinochloa scandens) but with much narrower leaves, its slender culms scramble to about 25 m over vegetation. Used, like other climbing bamboos, for weaving.",
  },
  "Cephalostachyum mindorense": {
    habit: "Clumping (sympodial), dense clumps of thin-walled weak culms; forest species",
    height: "small to medium (genus-level)",
    diameter: "slender, thin-walled (genus-level)",
    uses: "",
    description: "A very rare bamboo ('bagtok') endemic to the Philippines, growing in dense clumps of thin-walled, weak culms in humid, shady mountain-to-lowland forest. Species-level dimensions and specific uses are poorly documented; it has been studied for potential utilization.",
  },
  "Schizostachyum jaculans": {
    habit: "Clumping (sympodial), slender and erect with pendulous tip; mushroom-shaped crown",
    height: "6–10 m",
    diameter: "2–4 cm (thin-walled; very long internodes)",
    uses: "Blowpipes (joined internodes), woven mats (flattened culms), soil stabilization / erosion control",
    description: "A slender erect clumping bamboo ('blowpipe bamboo') with very long, thin-walled internodes and a mushroom-shaped crown; traditionally used to make blowpipes and also flattened for mat-weaving and planted for erosion control.",
  },
  "Bambusa vulgaris f. waminii": {
    habit: "Clumping (sympodial), dwarf; swollen lower internodes",
    height: "2–5 m",
    diameter: "up to ~10 cm (swollen basal internodes)",
    uses: "Ornamental (decorative hedges, garden accents, large containers); handicrafts",
    description: "The 'dwarf Buddha belly' — a compact clumping form of common bamboo with dramatically swollen lower internodes giving a pot-bellied look; grown almost entirely as an ornamental accent, hedge or container specimen, with culms occasionally used for handicraft.",
  },
  "Dinochloa dielsiana": {
    habit: "Climbing/scrambling (zigzag culms) (genus-level)",
    height: "climbing, several to many m (genus-level)",
    diameter: "1–4 cm (genus-level)",
    uses: "Weaving and basketry, rattan substitute (genus-level)",
    description: "A Philippine-endemic climbing bamboo ('tagisi') of the genus Dinochloa; like its relatives it has slender, zigzag culms that scramble over vegetation rather than standing erect. Species-specific dimensions are poorly documented, so genus-level traits are given.",
  },
  "Phyllostachys nigra f. nigra": {
    habit: "Running (monopodial), erect",
    height: "6–11 m",
    diameter: "2–5 cm",
    uses: "Ornamental specimen and screens; furniture, musical instruments, decorative inlays",
    description: "The typical black-culmed form of black bamboo — a running temperate species whose green culms mature to glossy jet-black; a prized ornamental screen or specimen that also yields wood for furniture, instruments and decorative work. Runs and needs containment.",
  },
  "Sasaella masamuneana": {
    habit: "Running (monopodial), dwarf groundcover",
    height: "0.6–1.8 m",
    diameter: "under 1 cm (slender)",
    uses: "Ornamental groundcover, lawn substitute, low edging, containers",
    description: "A dwarf running bamboo grown as a dense ornamental groundcover, with broad dark-green leaves (variegated white/cream in cultivated forms); it tolerates mowing and suits containers and low edging. Spreads by rhizomes but stays low.",
  },
  "Bambusa polymorpha": {
    habit: "Clumping (sympodial), densely tufted, tall and heavily branched",
    height: "15–25 m (to 30 m)",
    diameter: "7.5–15 cm (walls 1–2 cm, sometimes solid at base)",
    uses: "Building and construction (house frames, wattle-and-daub, ceilings, concrete reinforcement), furniture, pulp and paper, handicrafts, edible shoots, incense (agarbathi) sticks, fibreboard",
    description: "A tall, densely tufted clumping bamboo from Myanmar and India with striking grey-green to whitish culms and relatively thick walls; widely used for house construction, furniture, pulp and paper, and edible shoots. Grown here as an exotic.",
  },
  "Chimonobambusa sp.": {
    habit: "Running (monopodial) (genus-level)",
    height: "~2–7 m (genus-level)",
    diameter: "1–4 cm (genus-level)",
    uses: "Ornamental; walking sticks (some square-culmed); edible winter shoots (genus-level)",
    description: "Identified only to genus. Chimonobambusa is a group of running temperate bamboos (some with squarish culms) grown ornamentally and for edible winter shoots. The specific species in the collection is undetermined, so only genus-level traits are given.",
  },
};
